// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"GP_Clocklendar","status":true,"description":"Relógio para saber o tempo do dia","parameters":{"MinutesInDay":"30","NightTimeStart":"18:00","NightTimeEnd":"06:00","StartingDayHour":"2020-01-01 00:00"}},
{"name":"GP_Messages","status":false,"description":"","parameters":{}}
];
